'use strict'

export const TOGGLE_SELECT = 'TOGGLE_SELECT'
export const DELETE_PHOTOS = 'DELETE_PHOTOS'
export const TOGGLE_PERMISSION = 'TOGGLE_PERMISSION'
export const SET_ORDER = 'SET_ORDER'
export const CLEAR_CHANGE = 'CLEAR_CHANGE'
export const RESET_SELECT_COUNT = 'RESET_SELECT_COUNT'
